### ISSUE TITLE
Python3.6 TypeError: Class advice impossible in Python3.  Use the @implementer class decorator instead.

### ISSUE THREAD

**Issue by yashkumaratri** [zopefoundation/zope.interface#116]
Everytime I run nVidias supervised classifier the program throws

```
aurora@streak:~/Documents/sentiment-discoverylatest$ python3 generate.py --load_model sst_clf.pt --gen_length 200 --heatmap \         # model runs for 200 tokens total including generated and warm up tokens --text "25 August 2003 League of Extraordinary Gentlemen: Sean Connery is "
Traceback (most recent call last):
  File "generate.py", line 16, in <module>
    from apex.reparameterization import apply_weight_norm, remove_weight_norm
  File "/home/aurora/.local/lib/python3.6/site-packages/apex/__init__.py", line 18, in <module>
    from apex.interfaces import (ApexImplementation,
  File "/home/aurora/.local/lib/python3.6/site-packages/apex/interfaces.py", line 10, in <module>
    class ApexImplementation(object):
  File "/home/aurora/.local/lib/python3.6/site-packages/apex/interfaces.py", line 14, in ApexImplementation
    implements(IApex)
  File "/home/aurora/.local/lib/python3.6/site-packages/zope/interface/declarations.py", line 483, in implements
    raise TypeError(_ADVICE_ERROR % 'implementer')
TypeError: Class advice impossible in Python3.  Use the @implementer class decorator instead.
It shows error in zope.interface , So whats the trouble?
```

**Comment by jamadden** [comment]
This is the trouble:
```
  File "/home/aurora/.local/lib/python3.6/site-packages/apex/interfaces.py", line 14, in ApexImplementation
    implements(IApex)
```

The `apex` package is not compatible with Python 3. It's doing something like 
```python
from zope.interface import implements
class ApexImplementation(object):
    implements(IApex) # XXX: Bad!
```

But to work on Python 3 (while also remaining compatible with Python 2), that has to be:
```python
from zope.interface import implementer
@implementer(IApex)
class ApexImplementation(object):
    pass
```

At any rate, the problem is not here, it's with `apex`.

**Comment by mforbes** [comment]
Why is the first example in the documentation using the broken form.  Am I missing something?

**Comment by d-maurer** [comment]
Michael McNeil Forbes wrote at 2019-8-16 15:43 -0700:
>Why is the first example in the documentation using the broken form.  Am I missing something?

Because the documentation has not yet been updated for Python 3.
