### ISSUE TITLE
How to run tests without tox

### ISSUE THREAD

**Issue by frenzymadness** [zopefoundation/zope.interface#196]
Hello.

I am trying to update python-zope-interface RPM package in Fedora but I am not able to run tests during a build of RPM package. The problem is that I cannot use tox because I have to test the code which will be then packaged into RPM (from the folder called buildroot). When I do it, there is a lot of tests failing because the first level of package name is missing.

The package is installed in the stardard way in `/builddir/build/BUILDROOT/python-zope-interface-5.0.1-1.fc33.x86_64/usr/lib64/python3.8/site-packages` and I am in this folder.

```
# PURE_PYTHON=1 python3 -m unittest discover zope/
FAIL: test_no_existing (interface.tests.test_declarations.Test_classImplements)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILDROOT/python-zope-interface-5.0.1-1.fc33.x86_64/usr/lib64/python3.8/site-packages/zope/interface/tests/test_declarations.py", line 800, in test_no_existing
    self.assertEqual(spec.__name__,
AssertionError: 'interface.tests.test_declarations.Foo' != 'zope.interface.tests.test_declarations.Foo'
- interface.tests.test_declarations.Foo
+ zope.interface.tests.test_declarations.Foo
? +++++
```

I've tried also pytest:
```
# PURE_PYTHON=1 python3 -m pytest -x 
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.8.2, pytest-4.6.9, py-1.8.0, pluggy-0.13.0
rootdir: /builddir/build/BUILDROOT/python-zope-interface-5.0.1-1.fc33.x86_64/usr/lib64/python3.8/site-packages
collected 1239 items                                                                                                                                                                         

========================================================================================== FAILURES ==========================================================================================
__________________________________________________________________ Test_implementedByFallback.test_w_None_no_bases_w_class ___________________________________________________________________

self = <interface.tests.test_declarations.Test_implementedByFallback testMethod=test_w_None_no_bases_w_class>

    def test_w_None_no_bases_w_class(self):
        from zope.interface.declarations import ClassProvides
        class Foo(object):
            __implemented__ = None
        spec = self._callFUT(Foo)
>       self.assertEqual(spec.__name__,
                         'zope.interface.tests.test_declarations.Foo')
E       AssertionError: 'interface.tests.test_declarations.Foo' != 'zope.interface.tests.test_declarations.Foo'
E       - interface.tests.test_declarations.Foo
E       + zope.interface.tests.test_declarations.Foo
E       ? +++++

zope/interface/tests/test_declarations.py:551: AssertionError
====================================================================== 1 failed, 443 passed, 18 skipped in 1.86 seconds ======================================================================

```

Could you please help me to solve this issue? Might it be related to the fact that zope is a namespace package and its other parts are installed in a different location?

**Comment by jamadden** [comment]
Try running from the checkout/build directory.

```
$ tar -xf zope.interface.tar.gz
$ cd zope.interface
$ python setup.py build_ext -i
$ python -m unittest discover -s src
```

**Comment by frenzymadness** [comment]
> Try running from the checkout/build directory.
> 
> ```
> $ tar -xf zope.interface.tar.gz
> $ cd zope.interface
> $ python setup.py build_ext -i
> $ python -m unittest discover -s src
> ```

Thank you for the quick reply. I've already tried that but unfortunately, unittest does not like the situation when it should run tests from one folder/module but import tested module from a different location:

```
# PURE_PYTHON=1 PYTHONPATH=/builddir/build/BUILDROOT/python-zope-interface-5.0.1-1.fc33.x86_64/usr/lib64/python3.8/site-packages/ python3 -m unittest discover src
Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib64/python3.8/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/usr/lib64/python3.8/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python3.8/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib64/python3.8/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/usr/lib64/python3.8/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib64/python3.8/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib64/python3.8/unittest/loader.py", line 414, in _find_tests
    yield from self._find_tests(full_path, pattern, namespace)
  File "/usr/lib64/python3.8/unittest/loader.py", line 414, in _find_tests
    yield from self._find_tests(full_path, pattern, namespace)
  File "/usr/lib64/python3.8/unittest/loader.py", line 414, in _find_tests
    yield from self._find_tests(full_path, pattern, namespace)
  [Previous line repeated 1 more time]
  File "/usr/lib64/python3.8/unittest/loader.py", line 405, in _find_tests
    tests, should_recurse = self._find_test_path(
  File "/usr/lib64/python3.8/unittest/loader.py", line 458, in _find_test_path
    raise ImportError(
ImportError: 'test_builtins' module incorrectly imported from '/builddir/build/BUILDROOT/python-zope-interface-5.0.1-1.fc33.x86_64/usr/lib64/python3.8/site-packages/zope/interface/common/tests'. Expected '/builddir/build/BUILD/zope.interface-5.0.1/src/zope/interface/common/tests'. Is this module globally installed?
```

**Comment by jamadden** [comment]
OK. Then perhaps the `-t` option is what you need. This complete sequence worked for me.

```
$ mkvirtualenv
$ pip download zope.interface
$ tar -xf zope.interface-5.0.1.tar.gz
$ cd zope.interface-5.0.1
$ pip install .[test]
$ cd <site-packages>
$ python -m unittest discover -s zope/interface -t .
```

**Comment by d-maurer** [comment]
frenzymadness wrote at 2020-3-22 03:35 -0700:
>I am trying to update python-zope-interface RPM package in Fedora but I am not able to run tests during a build of RPM package. The problem is that I cannot use tox because I have to test the code which will be then packaged into RPM (from the folder called buildroot). When I do it, there is a lot of tests failing because the first level of package name is missing.

Maybe, you can use `zope.testrunner`?

I do not know the details, because I typically use
`zope.testrunner` indirectly via a small wrapper `dm.zopepatches.ztest`.
With it, the tests are run with `ztest -s zope.interface`.
Something similar should be possible with bare `zope.testrunner`.

**Comment by jamadden** [comment]
> Maybe, you can use `zope.testrunner`?

`zope.testrunner` has `zope.interface` as a direct dependency. That makes it complicated to use to run tests of the package under development.

**Comment by d-maurer** [comment]
Jason Madden wrote at 2020-3-22 07:08 -0700:
>> Maybe, you can use `zope.testrunner`?
>
>`zope.testrunner` has `zope.interface` as a direct dependency. That makes it complicated to use to run tests of the package under development.

`zope.testrunner` has only limited requirements regarding
`zope.interface`. It would still do its work even when `zope.interface`
had some deficiencies.

I just run the test via `ztest` (a tiny wrapper around `zope.testrunner`):
(py3) ztest -s zope.interface
...
  Ran 872 tests with 0 failures, 0 errors and 14 skipped in 0.138 seconds.
Tearing down left over layers:
  Tear down zope.testrunner.layer.UnitTests in 0.000 seconds.

**Comment by frenzymadness** [comment]
> OK. Then perhaps the `-t` option is what you need. This complete sequence worked for me.
> 
> ```
> $ mkvirtualenv
> $ pip download zope.interface
> $ tar -xf zope.interface-5.0.1.tar.gz
> $ cd zope.interface-5.0.1
> $ pip install .[test]
> $ cd <site-packages>
> $ python -m unittest discover -s zope/interface -t .
> ```

Awesome, thank you!

```
# pwd
/builddir/build/BUILDROOT/python-zope-interface-5.0.1-1.fc33.x86_64/usr/lib64/python3.8/site-packages
# PURE_PYTHON=1 python3 -m unittest discover -s zope/interface -t .
.........................................................s...............................................s......s.....s..............s.s...............................................s........................................................................................................................................................................................ssss..s..s.s.s.s..........ss......................................................................................s..........................................................................................................................................................................................................................................s........................................................................................................................................s............................................................................................................................................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 1235 tests in 0.419s

OK (skipped=21)
```
