### ISSUE TITLE
verifyClass(IAdapterRegistry, AdapterRegistry)...

### ISSUE THREAD

**Issue by liveFreeOrCode** [zopefoundation/zope.interface#208]
```
from zope.interface.adapter import AdapterRegistry, IAdapterRegistry

verifyClass(IAdapterRegistry, AdapterRegistry)
...
MultipleInvalid: The object <class 'zope.interface.adapter.AdapterRegistry'> has failed to implement interface <InterfaceClass zope.interface.interfaces.IAdapterRegistry>:
    The zope.interface.interfaces.IAdapterRegistry.lookup(required, provided, name='', default=None) attribute was not provided
    The zope.interface.interfaces.IAdapterRegistry.queryMultiAdapter(objects, provided, name='', default=None) attribute was not provided
    The zope.interface.interfaces.IAdapterRegistry.lookup1(required, provided, name='', default=None) attribute was not provided
    The zope.interface.interfaces.IAdapterRegistry.queryAdapter(object, provided, name='', default=None) attribute was not provided
    The zope.interface.interfaces.IAdapterRegistry.adapter_hook(provided, object, name='', default=None) attribute was not provided
    The zope.interface.interfaces.IAdapterRegistry.lookupAll(required, provided) attribute was not provided
    The zope.interface.interfaces.IAdapterRegistry.names(required, provided) attribute was not provided
    The contract of zope.interface.interfaces.IAdapterRegistry.subscribe(required, provided, subscriber, name='') is violated because 'BaseAdapterRegistry.subscribe(self, required, provided, value)' doesn't allow enough arguments
    The zope.interface.interfaces.IAdapterRegistry.subscriptions(required, provided, name='') attribute was not provided
    The zope.interface.interfaces.IAdapterRegistry.subscribers(objects, provided, name='') attribute was not provided
```

Is there something I'm missing?

**Comment by jamadden** [comment]
`verifyClass` can only check whether a class *statically* meets the requirements of an interface. `AdapterRegistry` does not statically meet the requirements of `IAdapterRegistry`, and `verifyClass` is correct to point that out. For example:
```pycon
>>> from zope.interface.adapter import AdapterRegistry
>>> AdapterRegistry.lookup
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'AdapterRegistry' has no attribute 'lookup'
```

This is because many attributes are delegated to a different object at runtime; that's part of the difference between `implements` and `provides`. https://github.com/zopefoundation/zope.interface/blob/10a951f9db32c3e3a29fef4e8b72e354b0c80047/src/zope/interface/adapter.py#L117-L120

(https://github.com/zopefoundation/zope.interface/issues/15 is somewhat similar).

Given the dynamic nature of python, and the distinction between `implements` and `provides` `verifyObject` is a better fit here. 

However, even doing that does appear to reveal a discrepancy:
```pycon
>>> from zope.interface import *
>>> from zope.interface.adapter import *
>>> from zope.interface.verify import *
>>> from zope.interface.interfaces import IAdapterRegistry
>>> verifyObject(IAdapterRegistry, AdapterRegistry())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//zope.interface/src/zope/interface/verify.py", line 172, in verifyObject
    return _verify(iface, candidate, tentative, vtype='o')
  File "//zope.interface/src/zope/interface/verify.py", line 92, in _verify
    raise MultipleInvalid(iface, candidate, excs)
zope.interface.exceptions.MultipleInvalid: The object <zope.interface.adapter.AdapterRegistry object at 0x10e8fd2d0> has failed to implement interface <InterfaceClass zope.interface.interfaces.IAdapterRegistry>:
    The contract of zope.interface.interfaces.IAdapterRegistry.subscribe(required, provided, subscriber, name='') is violated because 'BaseAdapterRegistry.subscribe(required, provided, value)' doesn't allow enough arguments
    The contract of zope.interface.interfaces.IAdapterRegistry.subscribers(objects, provided, name='') is violated because 'AdapterLookupBase.subscribers(objects, provided)' doesn't allow enough arguments
```

I don't know if this is due to a limitation in C extension methods, or to a problem in the interface definition. On a quick examination, it appears to be a problem with the interface.

```pycon
>>> reg = AdapterRegistry()
>>> reg.subscribe
<bound method BaseAdapterRegistry.subscribe of <zope.interface.adapter.AdapterRegistry object at 0x10e91f960>>
>>> help(reg.subscribe)
Help on method subscribe in module zope.interface.adapter:

subscribe(required, provided, value) method of zope.interface.adapter.AdapterRegistry instance

None
>>> reg.subscribe('req', 'prov', 'val', 'name')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: subscribe() takes 4 positional arguments but 5 were given
```
