### ISSUE TITLE
heads-up: test failures with Python 3.13~alpha1 - indentation doesn't match the expected

### ISSUE THREAD

**Issue by befeleme** [zopefoundation/zope.interface#279]
### What I did:

In Fedora Linux, we're attempting to rebuild the system with the early Python 3.13 releases.
The test failure happens with Python 3.13~alpha1 during the RPM build.

In [What's new in Python 3.13](https://docs.python.org/dev/whatsnew/3.13.html#removed) there's:

> Compiler now strip indents from docstrings. This will reduce the size of [bytecode cache](https://docs.python.org/dev/glossary.html#term-bytecode) (e.g. .pyc file). For example, cache file size for sqlalchemy.orm.session in SQLAlchemy 2.0 is reduced by about 5%. This change will affect tools using docstrings, like [doctest](https://docs.python.org/dev/library/doctest.html#module-doctest). (Contributed by Inada Naoki in [gh-81283](https://github.com/python/cpython/issues/81283).)

### What I expect to happen:
Successful build

### What actually happened:
```
+ python3 -m unittest discover -s zope/interface -t .
................................s......................s.........................................................ss.....s.............s.s..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................F..........F....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
======================================================================
FAIL: test_asReStructuredText_empty_with_multiline_docstring (zope.interface.tests.test_document.Test_asReStructuredText.test_asReStructuredText_empty_with_multiline_docstring)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILDROOT/python-zope-interface-6.0-2.fc40.x86_64/usr/lib64/python3.13/site-packages/zope/interface/tests/test_document.py", line 298, in test_asReStructuredText_empty_with_multiline_docstring
    self.assertEqual(self._callFUT(IEmpty), EXPECTED)
AssertionError: '``IE[39 chars]n \n It can be used to annotate any class or o[66 chars]\n\n' != '``IE[39 chars]n \n             It can be used to annotate an[90 chars]\n\n'
  ``IEmpty``
  
   This is an empty interface.
   
-  It can be used to annotate any class or object, because it promises
+              It can be used to annotate any class or object, because it promises
? ++++++++++++
-  nothing.
+              nothing.
  
   Attributes:
  
   Methods:
======================================================================
FAIL: test_asStructuredText_empty_with_multiline_docstring (zope.interface.tests.test_document.Test_asStructuredText.test_asStructuredText_empty_with_multiline_docstring)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILDROOT/python-zope-interface-6.0-2.fc40.x86_64/usr/lib64/python3.13/site-packages/zope/interface/tests/test_document.py", line 74, in test_asStructuredText_empty_with_multiline_docstring
    self.assertEqual(self._callFUT(IEmpty), EXPECTED)
AssertionError: 'IEmp[35 chars]n \n It can be used to annotate any class or o[66 chars]\n\n' != 'IEmp[35 chars]n \n             It can be used to annotate an[90 chars]\n\n'
  IEmpty
  
   This is an empty interface.
   
-  It can be used to annotate any class or object, because it promises
+              It can be used to annotate any class or object, because it promises
? ++++++++++++
-  nothing.
+              nothing.
  
   Attributes:
  
   Methods:

----------------------------------------------------------------------
Ran 1355 tests in 0.391s

FAILED (failures=2, skipped=7)
```

**Comment by icemac** [comment]
Thank you for reporting this issue, I'll activate Python 3.13 in GitHub actions to see if it comes this far.

**Comment by icemac** [comment]
This seems currently to be blocked by https://github.com/python-cffi/cffi/issues/23, so we'll probably will not get to a test run at all.

**Comment by frenzymadness** [comment]
Should the test for Python 3.13+ simply check the docstring without the indentation? Or is there any hidden meaning? I can prepare a PR and test it on Fedora.

**Comment by icemac** [comment]
The function under test converts the docstring to (re-)structured text. So the test for 3.13+ can just leave out the indentation.
