### ISSUE TITLE
Test failures with Python 3.13.0b1

### ISSUE THREAD

**Issue by mgorny** [zopefoundation/zope.interface#292]
### What I did:

1. Installed Python 3.13.0b1.
2. `tox -e py313`

### What I expect to happen:

Tests passing :-).

### What actually happened:

```pytb
$ tox -e py313
py313: recreate env because python changed version_info=[3, 13, 0, 'alpha', 6]->[3, 13, 0, 'beta', 1]
py313: remove tox env folder /tmp/zope.interface/.tox/py313
py313: install_deps> python -I -m pip install --pre Sphinx --pre
.pkg-cpython313: recreate env because python changed version_info=[3, 13, 0, 'alpha', 6]->[3, 13, 0, 'beta', 1]
.pkg-cpython313: remove tox env folder /tmp/zope.interface/.tox/.pkg-cpython313
.pkg-cpython313: install_requires> python -I -m pip install 'setuptools>=40.8.0' wheel
.pkg-cpython313: _optional_hooks> python /usr/lib/python3.12/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg-cpython313: get_requires_for_build_editable> python /usr/lib/python3.12/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg-cpython313: install_requires_for_build_editable> python -I -m pip install wheel
.pkg-cpython313: build_editable> python /usr/lib/python3.12/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
py313: install_package_deps> python -I -m pip install --pre Sphinx 'coverage>=5.0.3' repoze.sphinx.autointerface setuptools sphinx-rtd-theme zope.event zope.testing --pre
py313: install_package> python -I -m pip install --pre --force-reinstall --no-deps /tmp/zope.interface/.tox/.tmp/package/2/zope.interface-6.4.dev0-0.editable-cp313-cp313-linux_x86_64.whl --pre
py313: commands[0]> coverage run -p -m unittest discover -s src
E
======================================================================
ERROR: zope.interface (unittest.loader._FailedTest.zope.interface)
----------------------------------------------------------------------
ImportError: Failed to import test module: zope.interface
Traceback (most recent call last):
  File "/usr/lib/python3.13/unittest/loader.py", line 429, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib/python3.13/unittest/loader.py", line 339, in _get_module_from_name
    __import__(name)
    ~~~~~~~~~~^^^^^^
  File "/tmp/zope.interface/src/zope/interface/__init__.py", line 58, in <module>
    _wire()
    ~~~~~^^
  File "/tmp/zope.interface/src/zope/interface/interface.py", line 1117, in _wire
    from zope.interface.interfaces import IElement
  File "/tmp/zope.interface/src/zope/interface/interfaces.py", line 55, in <module>
    class IElement(Interface):
    ...<91 lines>...
            """
  File "/tmp/zope.interface/src/zope/interface/interface.py", line 774, in __init__
    self.__attrs = self.__compute_attrs(attrs)
                   ~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/tmp/zope.interface/src/zope/interface/interface.py", line 793, in __compute_attrs
    aname: update_value(aname, aval)
           ~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/tmp/zope.interface/src/zope/interface/interface.py", line 789, in update_value
    raise InvalidInterface("Concrete attribute, " + aname)
zope.interface.exceptions.InvalidInterface: Concrete attribute, __firstlineno__


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
py313: exit 1 (0.16 seconds) /tmp/zope.interface> coverage run -p -m unittest discover -s src pid=282042
  py313: FAIL code 1 (12.37=setup[12.21]+cmd[0.16] seconds)
  evaluation failed :( (12.96 seconds)
```

### What version of Python and Zope/Addons I am using:

Gentoo Linux amd64
CPython 3.13.0b1
zope.interface 78fdf3d0593dd8c937541959238cb0fe1a303a99

**Comment by mgorny** [comment]
After adding:

```diff
diff --git a/src/zope/interface/interface.py b/src/zope/interface/interface.py
index 733e395..8e0d9ad 100644
--- a/src/zope/interface/interface.py
+++ b/src/zope/interface/interface.py
@@ -802,6 +802,9 @@ class InterfaceClass(_InterfaceClassBase):
                 # __static_attributes__: Python 3.13a6+
                 # https://github.com/python/cpython/pull/115913
                 '__static_attributes__',
+                # __firstlineno__: Python 3.13b1+
+                # https://github.com/python/cpython/pull/118475
+                '__firstlineno__',
             )
             and aval is not _decorator_non_return
         }
```

I'm getting another test failure:

```pytb
======================================================================
FAIL: test_inside_function_call (zope.interface.tests.test_advice.FrameInfoTest.test_inside_function_call)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/zope.interface/src/zope/interface/tests/test_advice.py", line 57, in test_inside_function_call
    self.assertTrue(f_locals is locals()) # ???
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
AssertionError: False is not true
```

**Comment by hroncok** [comment]
I found a regression in Python 3.13.0b1 which involves `locals()`. It might be related to the later failure.

https://github.com/python/cpython/issues/118888

**Comment by musicinmybrain** [comment]
> I'm getting another test failure:
> 
> ```
> ======================================================================
> FAIL: test_inside_function_call (zope.interface.tests.test_advice.FrameInfoTest.test_inside_function_call)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/tmp/zope.interface/src/zope/interface/tests/test_advice.py", line 57, in test_inside_function_call
>     self.assertTrue(f_locals is locals()) # ???
>     ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
> AssertionError: False is not true
> ```

This is probably related to [PEP 667](https://peps.python.org/pep-0667/). The `frame.f_locals` is now a write-through proxy object of type `FrameLocalsProxy`.
