### ISSUE TITLE
zope.interface raises unhelpful "TypeError: Error when calling the metaclass bases" upon an invalid interface

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/zope.interface#5]
In https://bugs.launchpad.net/zope.interface/+bug/149544, @kumar303 reports:

> Since it took me so long to debug a traceback that looked like this:

```
Traceback (most recent call last):
...
File "/Users/kumar/src/zope.interface/src/zope/interface/advice.py", line 132, in advise
    return callback(newClass)
File "/Users/kumar/src/zope.interface/src/zope/interface/declarations.py", line 485, in _implements_advice
    classImplements(cls, *interfaces)
File "/Users/kumar/src/zope.interface/src/zope/interface/declarations.py", line 462, in classImplements
    spec.declared += tuple(_normalizeargs(interfaces))
File "/Users/kumar/src/zope.interface/src/zope/interface/declarations.py", line 1372, in _normalizeargs
    _normalizeargs(v, output)
File "/Users/kumar/src/zope.interface/src/zope/interface/declarations.py", line 1371, in _normalizeargs
    for v in sequence:
TypeError: Error when calling the metaclass bases
    iteration over non-sequence
```

> I thought I would take 5 minutes and submit a patch for a better error. I don't see any harm in catching the TypeError produced by trying to iterate sequence so this should be safe. If you're wondering what would cause an error like this, just google for "zope.interface TypeError: Error when calling the metaclass bases" ... there are a lot of hits. For a more specific example, this other bug motivated me to write this one :) -- https://bugs.launchpad.net/zope3/+bug/149517

And includes a patch:

> This patch is against trunk, r 80666. It includes a test and didn't break any existing tests.

  https://bugs.launchpad.net/zope.interface/+bug/149544/+attachment/155306/+files/zope_interface_better_error.patch

**Comment by jamadden** [comment]
This is not a problem with the current form, `@implementer()`. In both Python 3 and Python 2 (and with both old and new-style classes for both the target and the "interface"), the reasonable error "TypeError: 'type' object is not iterable" is produced.

```pycon
>>> zope.interface import *
>>> class Foo(object):
...    pass
...
>>> @implementer(Foo)
... class Bar(object):
...    pass
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "//src/zope/interface/declarations.py", line 553, in __call__
    classImplements(ob, *self.interfaces)
  File "//src/zope/interface/declarations.py", line 453, in classImplements
    interfaces = tuple(_normalizeargs(interfaces))
  File "//src/zope/interface/declarations.py", line 1114, in _normalizeargs
    _normalizeargs(v, output)
  File "//src/zope/interface/declarations.py", line 1113, in _normalizeargs
    for v in sequence:
TypeError: 'type' object is not iterable
```

This is *only* an issue with the deprecated inline form, which of course only works in Python 2.

```pycon
>>> class Bar:
...     implements(Foo)
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ... 
  File "//src/zope/interface/declarations.py", line 1113, in _normalizeargs
    for v in sequence:
TypeError: Error when calling the metaclass bases
    'type' object is not iterable
```

Because that form is deprecated, I think this can be closed as 'wontfix'.
