### ISSUE TITLE
regression in 4.3.0

### ISSUE THREAD

**Issue by mmerickel** [zopefoundation/zope.interface#53]
4.3.0 broke almost every single test in pyramid's test suite and appears to be related to https://github.com/zopefoundation/zope.interface/issues/46

See https://travis-ci.org/Pylons/pyramid/jobs/156458742 for an example or a snippet pasted below (all the failures look the same):

```
ERROR: test_authenticated_userid_fails_cleaning_as_Authenticated (pyramid.tests.test_authentication.TestCallbackAuthenticationPolicyDebugging)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Pylons/pyramid/pyramid/tests/test_authentication.py", line 12, in setUp
    self.config = testing.setUp()
  File "/home/travis/build/Pylons/pyramid/pyramid/testing.py", line 470, in setUp
    config._set_settings(settings)
  File "/home/travis/build/Pylons/pyramid/pyramid/config/settings.py", line 15, in _set_settings
    self.registry.settings = settings
  File "/home/travis/build/Pylons/pyramid/pyramid/registry.py", line 99, in _set_settings
    self.registerUtility(settings, ISettings)
  File "/home/travis/build/Pylons/pyramid/.tox/py27/lib/python2.7/site-packages/zope/interface/registry.py", line 227, in registerUtility
    _UtilityRegistrations.for_components(self).registerUtility(provided, name, component, info, factory)
  File "/home/travis/build/Pylons/pyramid/.tox/py27/lib/python2.7/site-packages/zope/interface/registry.py", line 82, in for_components
    regs = cls._regs_for_components[components]
  File "/opt/python/2.7.9/lib/python2.7/weakref.py", line 315, in __getitem__
    return self.data[ref(key)]
TypeError: unhashable type: 'Registry'
```

**Comment by mmerickel** [comment]
This issue presents itself in production as well. Not just in the test suite.

**Comment by jamadden** [comment]
Pyramid uses multiple-inheritance [to subclass `Components` *and* `dict`](https://github.com/Pylons/pyramid/blob/master/pyramid/registry.py#L19), hence leading to this issue. I guess we'll have to figure out another way to associate the necessary data.

**Comment by icemac** [comment]
Fix released in 4.3.1.

**Comment by icemac** [comment]
@mmerickel Please test using 4.3.1 in Pyramid.

**Comment by jamadden** [comment]
Locally I get a clean run of the Pyramid tests using 4.3.1 (and I reproduce the failures with 4.3.0).

**Comment by stevepiercy** [comment]
Looks good in pyramid_jinja2, which depends on Pyramid https://travis-ci.org/Pylons/pyramid_jinja2/builds/156490621

Thank you for the quick turnaround.

**Comment by bertjwregeer** [comment]
Pyramid is once again building on Travis: https://travis-ci.org/Pylons/pyramid/builds/156458741

**Comment by mmerickel** [comment]
@icemac, @jamadden  Thank you for the quick fix!
