### ISSUE TITLE
Assignment to __class__ is broken

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/zope.interface#6]
In https://bugs.launchpad.net/zope.interface/+bug/180844, @jimfulton reports:

> See: http://mail.zope.org/pipermail/interface-dev/2008-January/000192.html
> 
> Here's an example that provides the basis for a test case:

```pycon
>>> import zope.interface.interface
>>> class InterfaceClass(zope.interface.interface.InterfaceClass):
...     def __call__(self, *args):
...         print 'called', self, args
...
>>> IFoo = InterfaceClass('IFoo', (zope.interface.Interface,))
>>> IFoo(1)
called <InterfaceClass __main__.IFoo> (1,)
>>> class IBar(IFoo): pass
...
>>> IBar()
called <InterfaceClass __main__.IBar> ()
>>> class ISpam(zope.interface.Interface): pass
...
>>> ISpam()
Traceback (most recent call last):
    File "<console>", line 1, in ?
TypeError: function takes at least 1 argument (0 given)
>>> ISpam.__class__ = InterfaceClass
>>> ISpam()
Traceback (most recent call last):
    File "<console>", line 1, in ?
TypeError: function takes at least 1 argument (0 given)
```

**Comment by jamadden** [comment]
This works as requested using the pure-Python implementation but fails with the C accelerator.
